name: Publish GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Copy External Images
      - run: |
        mkdir images
        curl -o images/0.jpg http://keisotsuna.servebeer.com:9000/PCWorld/0.jpg
      - uses: actions/upload-artifact@v3
        with:
          name: my_site
          path: images
      - uses: actions/upload-pages-artifact@v1
        with:
          path: ./images

  deploy:
    needs: build
    runs-on: ubuntu-latest 
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/deploy-pages@v1
        id: deployment