name: Publish GitHub Pages

on:
  push:

# 書き込み権限の付与
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Copy External Images
      run: |
        mkdir -p ./images
        curl -o ./images/0.jpg http://keisotsuna.servebeer.com:9000/PCWorld/0.jpg

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./images