name: Keepalive Workflow

on:
  schedule:
    - cron: '0 0 1 * *' # 毎月1日に実行
  workflow_dispatch: # 手動でも実行できるようにする

jobs:
  keepalive:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Keepalive Commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit --allow-empty -m "chore: keepalive commit to prevent workflow suspension"
          git push
