name: Publish GitHub Pages

on:
  workflow_dispatch:
  repository_dispatch:
    types: [build_and_deploy]
    
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Inspect files before checkout
        run: ls -la
      - name: show current directory before checkout
        run: pwd
      - uses: actions/checkout@v3
      - name: Inspect files after checkout
        run: ls -la
      - name: show current directory after checkout
        run: pwd
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install npm Package
        run: |
          PUPPETEER_SKIP_DOWNLOAD=true PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true npm ci
      - name: copyfiles
        run: |
          for platform in PC Quest; do
            for i in {0..35}; do
              curl -s -f -o work/base_${platform}_${i}.jpg "https://namanonamako.github.io/world-discover-poster/base_${platform}_${i}.jpg" || true
              curl -s -f -o work/base_${platform}_d_${i}.jpg "https://namanonamako.github.io/world-discover-poster/base_${platform}_d_${i}.jpg" || true
            done
          done
          curl -s -f -o work/posterInfo.json https://namanonamako.github.io/world-discover-poster/posterInfo.json || true
          curl -s -f -o work/posterData.json http://keisotsuna.servebeer.com:9000/posterData.json || rm -f work/posterData.json
      - name: Set UTF-8 locale
        run: sudo apt-get update && sudo apt-get install -y language-pack-ja && sudo update-locale LANG=ja_JP.UTF-8
      - name: Install Japanese fonts
        run: sudo apt-get install -y fonts-noto-cjk
      - name: start action...
        run: >
          node app.js
      - name: check results
        run: >
          ls -ltr images
      - uses: actions/upload-artifact@v4
        with:
          name: my_site
          path: images
      - uses: actions/upload-pages-artifact@v3
        with:
          path: images

  deploy:
    needs: build
    runs-on: ubuntu-latest 
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
