name: Publish GitHub Pages

on:
  workflow_dispatch:
  repository_dispatch:
    types: [build_and_deploy]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Inspect files before checkout
        run: ls -la
      - name: show current directory before checkout
        run: pwd
      - uses: actions/checkout@v3
      - name: Inspect files after checkout
        run: ls -la
      - name: show current directory after checkout
        run: pwd
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      # キャッシュ
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      - name: Install npm Package
        run: npm install
      - name: copyfiles
        run: |
          curl -o work/base_PC_0.jpg https://namanonamako.github.io/poster_test/base_PC_0.jpg
          curl -o work/base_PC_1.jpg https://namanonamako.github.io/poster_test/base_PC_1.jpg
          curl -o work/base_PC_2.jpg https://namanonamako.github.io/poster_test/base_PC_2.jpg
          curl -o work/base_PC_3.jpg https://namanonamako.github.io/poster_test/base_PC_3.jpg
          curl -o work/base_PC_4.jpg https://namanonamako.github.io/poster_test/base_PC_4.jpg
          curl -o work/base_PC_5.jpg https://namanonamako.github.io/poster_test/base_PC_5.jpg
          curl -o work/base_PC_6.jpg https://namanonamako.github.io/poster_test/base_PC_6.jpg
          curl -o work/base_PC_7.jpg https://namanonamako.github.io/poster_test/base_PC_7.jpg
          curl -o work/base_PC_8.jpg https://namanonamako.github.io/poster_test/base_PC_8.jpg
          curl -o work/base_PC_9.jpg https://namanonamako.github.io/poster_test/base_PC_9.jpg
          curl -o work/base_PC_10.jpg https://namanonamako.github.io/poster_test/base_PC_10.jpg
          curl -o work/base_PC_11.jpg https://namanonamako.github.io/poster_test/base_PC_11.jpg
          curl -o work/base_Quest_0.jpg https://namanonamako.github.io/poster_test/base_Quest_0.jpg
          curl -o work/base_Quest_1.jpg https://namanonamako.github.io/poster_test/base_Quest_1.jpg
          curl -o work/base_Quest_2.jpg https://namanonamako.github.io/poster_test/base_Quest_2.jpg
          curl -o work/base_Quest_3.jpg https://namanonamako.github.io/poster_test/base_Quest_3.jpg
          curl -o work/base_Quest_4.jpg https://namanonamako.github.io/poster_test/base_Quest_4.jpg
          curl -o work/base_Quest_5.jpg https://namanonamako.github.io/poster_test/base_Quest_5.jpg
          curl -o work/base_Quest_6.jpg https://namanonamako.github.io/poster_test/base_Quest_6.jpg
          curl -o work/base_Quest_7.jpg https://namanonamako.github.io/poster_test/base_Quest_7.jpg
          curl -o work/base_Quest_8.jpg https://namanonamako.github.io/poster_test/base_Quest_8.jpg
          curl -o work/base_Quest_9.jpg https://namanonamako.github.io/poster_test/base_Quest_9.jpg
          curl -o work/base_Quest_10.jpg https://namanonamako.github.io/poster_test/base_Quest_10.jpg
          curl -o work/base_Quest_11.jpg https://namanonamako.github.io/poster_test/base_Quest_11.jpg
          curl -o work/posterInfo.json https://namanonamako.github.io/poster_test/posterInfo.json
          curl -o work/posterData.json http://keisotsuna.servebeer.com:9000/posterData.json
      - name: Set UTF-8 locale
        run: sudo apt-get install -y language-pack-ja && sudo update-locale LANG=ja_JP.UTF-8
      - name: Install Japanese fonts
        run: sudo apt-get install -y fonts-noto-cjk
      - name: start action...
        run: >
          node app.js
      - name: check results
        run: >
          ls -ltr images
      - uses: actions/upload-artifact@v3
        with:
          name: my_site
          path: images
      - uses: actions/upload-pages-artifact@v1
        with:
          path: images

  deploy:
    needs: build
    runs-on: ubuntu-latest 
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/deploy-pages@v1
        id: deployment
