name: Publish GitHub Pages

on:
  workflow_dispatch:
  repository_dispatch:
    types: [build_and_deploy]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Inspect files before checkout
        run: ls -la
      - name: show current directory before checkout
        run: pwd
      - uses: actions/checkout@v3
      - name: Inspect files after checkout
        run: ls -la
      - name: show current directory after checkout
        run: pwd
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      # キャッシュ
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      - name: Install npm Package
        run: npm install
      - name: copyfiles
        run: |
          curl -o work/base_PC_0.jpg https://namanonamako.github.io/world-discover-poster/base_PC_0.jpg
          curl -o work/base_PC_1.jpg https://namanonamako.github.io/world-discover-poster/base_PC_1.jpg
          curl -o work/base_PC_2.jpg https://namanonamako.github.io/world-discover-poster/base_PC_2.jpg
          curl -o work/base_PC_3.jpg https://namanonamako.github.io/world-discover-poster/base_PC_3.jpg
          curl -o work/base_PC_4.jpg https://namanonamako.github.io/world-discover-poster/base_PC_4.jpg
          curl -o work/base_PC_5.jpg https://namanonamako.github.io/world-discover-poster/base_PC_5.jpg
          curl -o work/base_PC_6.jpg https://namanonamako.github.io/world-discover-poster/base_PC_6.jpg
          curl -o work/base_PC_7.jpg https://namanonamako.github.io/world-discover-poster/base_PC_7.jpg
          curl -o work/base_PC_8.jpg https://namanonamako.github.io/world-discover-poster/base_PC_8.jpg
          curl -o work/base_PC_9.jpg https://namanonamako.github.io/world-discover-poster/base_PC_9.jpg
          curl -o work/base_PC_10.jpg https://namanonamako.github.io/world-discover-poster/base_PC_10.jpg
          curl -o work/base_PC_11.jpg https://namanonamako.github.io/world-discover-poster/base_PC_11.jpg
          curl -o work/base_PC_12.jpg https://namanonamako.github.io/world-discover-poster/base_PC_12.jpg
          curl -o work/base_PC_13.jpg https://namanonamako.github.io/world-discover-poster/base_PC_13.jpg
          curl -o work/base_PC_14.jpg https://namanonamako.github.io/world-discover-poster/base_PC_14.jpg
          curl -o work/base_PC_15.jpg https://namanonamako.github.io/world-discover-poster/base_PC_15.jpg
          curl -o work/base_PC_16.jpg https://namanonamako.github.io/world-discover-poster/base_PC_16.jpg
          curl -o work/base_PC_17.jpg https://namanonamako.github.io/world-discover-poster/base_PC_17.jpg
          curl -o work/base_PC_18.jpg https://namanonamako.github.io/world-discover-poster/base_PC_18.jpg
          curl -o work/base_PC_19.jpg https://namanonamako.github.io/world-discover-poster/base_PC_19.jpg
          curl -o work/base_PC_20.jpg https://namanonamako.github.io/world-discover-poster/base_PC_20.jpg
          curl -o work/base_PC_21.jpg https://namanonamako.github.io/world-discover-poster/base_PC_21.jpg
          curl -o work/base_PC_22.jpg https://namanonamako.github.io/world-discover-poster/base_PC_22.jpg
          curl -o work/base_PC_23.jpg https://namanonamako.github.io/world-discover-poster/base_PC_23.jpg
          curl -o work/base_PC_24.jpg https://namanonamako.github.io/world-discover-poster/base_PC_24.jpg
          curl -o work/base_PC_25.jpg https://namanonamako.github.io/world-discover-poster/base_PC_25.jpg
          curl -o work/base_PC_26.jpg https://namanonamako.github.io/world-discover-poster/base_PC_26.jpg
          curl -o work/base_PC_27.jpg https://namanonamako.github.io/world-discover-poster/base_PC_27.jpg
          curl -o work/base_PC_28.jpg https://namanonamako.github.io/world-discover-poster/base_PC_28.jpg
          curl -o work/base_PC_29.jpg https://namanonamako.github.io/world-discover-poster/base_PC_29.jpg
          curl -o work/base_PC_30.jpg https://namanonamako.github.io/world-discover-poster/base_PC_30.jpg
          curl -o work/base_PC_31.jpg https://namanonamako.github.io/world-discover-poster/base_PC_31.jpg
          curl -o work/base_PC_32.jpg https://namanonamako.github.io/world-discover-poster/base_PC_32.jpg
          curl -o work/base_PC_33.jpg https://namanonamako.github.io/world-discover-poster/base_PC_33.jpg
          curl -o work/base_PC_34.jpg https://namanonamako.github.io/world-discover-poster/base_PC_34.jpg
          curl -o work/base_PC_35.jpg https://namanonamako.github.io/world-discover-poster/base_PC_35.jpg
          curl -o work/base_Quest_0.jpg https://namanonamako.github.io/world-discover-poster/base_Quest_0.jpg
          curl -o work/base_Quest_1.jpg https://namanonamako.github.io/world-discover-poster/base_Quest_1.jpg
          curl -o work/base_Quest_2.jpg https://namanonamako.github.io/world-discover-poster/base_Quest_2.jpg
          curl -o work/base_Quest_3.jpg https://namanonamako.github.io/world-discover-poster/base_Quest_3.jpg
          curl -o work/base_Quest_4.jpg https://namanonamako.github.io/world-discover-poster/base_Quest_4.jpg
          curl -o work/base_Quest_5.jpg https://namanonamako.github.io/world-discover-poster/base_Quest_5.jpg
          curl -o work/base_Quest_6.jpg https://namanonamako.github.io/world-discover-poster/base_Quest_6.jpg
          curl -o work/base_Quest_7.jpg https://namanonamako.github.io/world-discover-poster/base_Quest_7.jpg
          curl -o work/base_Quest_8.jpg https://namanonamako.github.io/world-discover-poster/base_Quest_8.jpg
          curl -o work/base_Quest_9.jpg https://namanonamako.github.io/world-discover-poster/base_Quest_9.jpg
          curl -o work/base_Quest_10.jpg https://namanonamako.github.io/world-discover-poster/base_Quest_10.jpg
          curl -o work/base_Quest_11.jpg https://namanonamako.github.io/world-discover-poster/base_Quest_11.jpg
          curl -o work/base_Quest_12.jpg https://namanonamako.github.io/world-discover-poster/base_Quest_12.jpg
          curl -o work/base_Quest_13.jpg https://namanonamako.github.io/world-discover-poster/base_Quest_13.jpg
          curl -o work/base_Quest_14.jpg https://namanonamako.github.io/world-discover-poster/base_Quest_14.jpg
          curl -o work/base_Quest_15.jpg https://namanonamako.github.io/world-discover-poster/base_Quest_15.jpg
          curl -o work/base_Quest_16.jpg https://namanonamako.github.io/world-discover-poster/base_Quest_16.jpg
          curl -o work/base_Quest_17.jpg https://namanonamako.github.io/world-discover-poster/base_Quest_17.jpg
          curl -o work/base_Quest_18.jpg https://namanonamako.github.io/world-discover-poster/base_Quest_18.jpg
          curl -o work/base_Quest_19.jpg https://namanonamako.github.io/world-discover-poster/base_Quest_19.jpg
          curl -o work/base_Quest_20.jpg https://namanonamako.github.io/world-discover-poster/base_Quest_20.jpg
          curl -o work/base_Quest_21.jpg https://namanonamako.github.io/world-discover-poster/base_Quest_21.jpg
          curl -o work/base_Quest_22.jpg https://namanonamako.github.io/world-discover-poster/base_Quest_22.jpg
          curl -o work/base_Quest_23.jpg https://namanonamako.github.io/world-discover-poster/base_Quest_23.jpg
          curl -o work/base_Quest_24.jpg https://namanonamako.github.io/world-discover-poster/base_Quest_24.jpg
          curl -o work/base_Quest_25.jpg https://namanonamako.github.io/world-discover-poster/base_Quest_25.jpg
          curl -o work/base_Quest_26.jpg https://namanonamako.github.io/world-discover-poster/base_Quest_26.jpg
          curl -o work/base_Quest_27.jpg https://namanonamako.github.io/world-discover-poster/base_Quest_27.jpg
          curl -o work/base_Quest_28.jpg https://namanonamako.github.io/world-discover-poster/base_Quest_28.jpg
          curl -o work/base_Quest_29.jpg https://namanonamako.github.io/world-discover-poster/base_Quest_29.jpg
          curl -o work/base_Quest_30.jpg https://namanonamako.github.io/world-discover-poster/base_Quest_30.jpg
          curl -o work/base_Quest_31.jpg https://namanonamako.github.io/world-discover-poster/base_Quest_31.jpg
          curl -o work/base_Quest_32.jpg https://namanonamako.github.io/world-discover-poster/base_Quest_32.jpg
          curl -o work/base_Quest_33.jpg https://namanonamako.github.io/world-discover-poster/base_Quest_33.jpg
          curl -o work/base_Quest_34.jpg https://namanonamako.github.io/world-discover-poster/base_Quest_34.jpg
          curl -o work/base_Quest_35.jpg https://namanonamako.github.io/world-discover-poster/base_Quest_35.jpg
          curl -o work/posterInfo.json https://namanonamako.github.io/world-discover-poster/posterInfo.json
          curl -o work/posterData.json http://keisotsuna.servebeer.com:9000/posterData.json
      - name: Set UTF-8 locale
        run: sudo apt-get update && sudo apt-get install -y language-pack-ja && sudo update-locale LANG=ja_JP.UTF-8
      - name: Install Japanese fonts
        run: sudo apt-get install -y fonts-noto-cjk
      - name: start action...
        run: >
          node app.js
      - name: check results
        run: >
          ls -ltr images
      - uses: actions/upload-artifact@v4
        with:
          name: my_site
          path: images
      - uses: actions/upload-pages-artifact@v1
        with:
          path: images

  deploy:
    needs: build
    runs-on: ubuntu-latest 
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/deploy-pages@v1
        id: deployment
